import { Header } from '@/components/Header'
import '../styles/output.css'
import '../styles/fonts.css'

export const metadata = {
  title: 'YMovier',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
