import { Header } from '@/components/Header'
import '../styles/output.css'
import { Footer } from '@/components/Footer'
import { Ubuntu, Poppins } from 'next/font/google'
import { Metadata } from 'next'

export const ubuntu = Ubuntu({
  weight: ['300', '400', '500', '700'],
  variable: '--font-ubuntu',
  subsets: ['latin']
})

export const poppins = Poppins({
  weight:  '900',
  subsets: ['latin'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: 'YMovier',
  description: 'Generated by create next app'
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
