import { Header } from '@/components/Header'
import '../styles/output.css'
import '../styles/fonts.css'
import { Footer } from '@/components/Footer'
import { Ubuntu, Poppins } from 'next/font/google'

export const ubuntu = Ubuntu({
  weight: ['300', '400', '500', '700'],
  variable: '--font-ubuntu',
  subsets: ['latin']
})

export const poppins = Poppins({
  weight: ['800', '900'],
  subsets: ['latin'],
  variable: '--font-poppins',
})

export const metadata = {
  title: 'YMovier',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${ubuntu.variable} ${poppins.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
